### ISSUE TITLE
Compatibility Issue with @shopify/react-native-skia > 1.9.1

### ISSUE THREAD

**Issue by gspsteve** [FormidableLabs/victory-native-xl#497]
Describe Your Environment
victory-native-xl version: 41.16.1 (replace with the actual version)
React version: 18.3.1
React Native version: 0.76.3
Reanimated version: 3.16.3
React Native Skia version: 1.11.5 (broken), 1.9.1 (working)
Are you using Expo or React Native CLI? Expo
Platform: Both

Describe the Problem
🐛 Bug Report: victory-native-xl Incompatible with @shopify/react-native-skia >= 1.10.0
Issue Summary
Updating @shopify/react-native-skia to 1.10.x or 1.11.x breaks victory-native-xl, resulting in this error:

vbnet
Kopieren
Bearbeiten
TypeError: Skia.Recorder is not a function
🔹 Last working version of Skia: 1.9.1 🔹 Broken versions: 1.10.x, 1.11.x

Steps to Reproduce
1️⃣ Install victory-native-xl and @shopify/react-native-skia@1.11.5 2️⃣ Render a simple <VictoryChart> component 3️⃣ Run the app 4️⃣ Observe the error: TypeError: Skia.Recorder is not a function

Expected Behavior
victory-native-xl should work with the latest versions of @shopify/react-native-skia.
No Skia.Recorder error should occur.

**Comment by keithluchtel** [comment]
@gspsteve are you using Expo Go?  Expo Go currently ships with skia version `1.5.0` and is what should be used with Expo Go.

**Comment by gspsteve** [comment]
> [@gspsteve](https://github.com/gspsteve) are you using Expo Go? Expo Go currently ships with skia version `1.5.0` and is what should be used.

No, I’m using an Expo Dev Build.
I just hadn’t updated my development build after upgrading to Skia version to 1.11.5. Now that I’ve updated the dev build, everything seems to work fine.
